@startuml
start

:志愿者访问系统首页;

if (是否已登录?) then (否)
  :进入登录页面;
  if (是否已有账号?) then (否)
    :进入注册页面;
    :填写注册信息;
    :提交注册申请;
    :系统验证信息;
    if (验证通过?) then (是)
      :创建账号;
      :返回登录页面;
    else (否)
      :显示错误信息;
      :返回注册页面;
    endif
  else (是)
    :输入账号密码;
    :系统验证登录;
    if (验证通过?) then (是)
      :进入系统首页;
    else (否)
      :显示错误信息;
      :返回登录页面;
    endif
  endif
else (是)
  :直接进入系统首页;
endif

:查看活动列表;
if (是否查看活动详情?) then (是)
  :进入活动详情页;
  :查看活动信息;
  if (是否报名活动?) then (是)
    :提交报名申请;
    :系统处理报名;
    if (报名成功?) then (是)
      :等待活动开始;
      :参加活动;
      :活动结束后评分;
      :提交活动评价;
      :系统记录评分和评价;
    else (否)
      :显示报名失败信息;
      :返回活动列表;
    endif
  else (否)
    :返回活动列表;
  endif
else (否)
  :继续浏览活动列表;
endif

if (是否查看论坛?) then (是)
  :进入论坛页面;
  :浏览帖子;
  if (是否发帖?) then (是)
    :编写帖子内容;
    :提交帖子;
    :系统发布帖子;
  endif
  if (是否回复帖子?) then (是)
    :编写回复内容;
    :提交回复;
    :系统发布回复;
  endif
endif

if (是否查看公告?) then (是)
  :进入公告页面;
  :浏览公告信息;
endif

if (是否联系客服?) then (是)
  :进入客服聊天页面;
  :发送消息;
  :等待客服回复;
endif

:退出系统;
stop

@enduml 