/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    BreadCrumbs: typeof import('./components/common/BreadCrumbs.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    ExcelFileUpload: typeof import('./components/common/ExcelFileUpload.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    HomeCard: typeof import('./components/home/HomeCard.vue')['default']
    HomeChart: typeof import('./components/home/HomeChart.vue')['default']
    HomeComment: typeof import('./components/home/HomeComment.vue')['default']
    HomeProgress: typeof import('./components/home/HomeProgress.vue')['default']
    IndexAside: typeof import('./components/index/IndexAside.vue')['default']
    IndexAsideStatic: typeof import('./components/index/IndexAsideStatic.vue')['default']
    IndexAsideSub: typeof import('./components/index/IndexAsideSub.vue')['default']
    IndexHeader: typeof import('./components/index/IndexHeader.vue')['default']
    IndexMain: typeof import('./components/index/IndexMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
  }
}
